### ISSUE TITLE
Couldn't run the app in examples

### ISSUE THREAD

**Issue by abhisb** [justin-john/elet#1]
- As the `node_modules` is within the `examples` folder and `elet.js` wouldn't able to access the swig module. 
- Issue will be fixed when adding the `node_modules` in the `root directory`.

**Comment by justin-john** [comment]
Thank you for raising the issue. Yes, you are correct on node_modules in  root directory and examples directory needs  be application root directory. The [read-me](https://github.com/justin-john/elet/blob/master/examples/README.md) file explains how to run example application. If you like to update read-me doc more clearly, please let me know as I can give you write access to repository.
